---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    env: swiggy
    proj: zomato
spec:
  containers:
  - name: cont-1
    image: 7674043534/devrepo
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 3
  selector:
    matchLabels:
      env: swiggy
  template:
    metadata:
      labels:
        env: swiggy
    spec:
      containers:
      - name: cont-1
        image: 7674043534/devrepo
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 2
  selector:
    matchLabels:
      env: swiggy
  template:
    metadata:
      labels:
        env: swiggy
    spec:
      containers:
      - name: cont-1
        image: 7674043534/devrepo
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    type: ClusterIP
    env: swiggy
  ports:
  - port: 80
    targetPort: 80
